name: Build Desktop
description: ""

inputs:
  package-id:
    description: 'Compiled Package ID'
    required: true
    default: 'release_Windows'
  project-to-build:
    description: 'Relative path to .csproj file'
    required: true
    default: ''
  project-platform:
    description: 'Platform to build'
    required: false
    default: 'x86'
  artifact-retention-policy: 
    description: 'Number of days to keep the build artifacts'
    required: false
    default: '90'
  is-gtk: 
    description: 'If true, current step will install GTK4'
    required: false
    default: 'false'    
runs:
  using: "composite"
  steps:
    - name: Setup GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.9
      with:
        versionSpec: '5.x'

    - name: GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.9
      with:
        useConfigFile: true
        configFilePath: ./.github/workflows/config/gitversion.yml

    # Install GTK4
    - name: Install GTK4
      continue-on-error: true
      shell: pwsh
      run: |
          if ('true' -eq '${{ inputs.is-gtk }}') {
            Write-Host "Installing GTK4"
            Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
            choco install git
            choco install msys2
            choco install visualstudio2022-workload-vctools

            Write-Host "Installing Python"
            choco install python
            Write-Host "Python Installation Finished"

            python -m pip install --user pipx
            python -m pipx ensurepath
            pipx install gvsbuild
            
            gvsbuild build gtk4

            Write-Host "Adding GTK4 to Path"
            $env:Path = "C:\gtk-build\gtk\x64\release\bin;" + $env:Path
            Write-Host "GTK4 Installation Finished"
          }

    - name: Sleep for 15s to release dotnet.exe
      run: Start-Sleep -s 15
      shell: pwsh        

    # Create the app package by building and packaging the project
    - name: Build and Create Package
      shell: pwsh
      run: |
        Write-Host  ""
        Write-Host "Building ${{ inputs.package-id }}"
        dotnet build  -c Release -p:Platform=${{ inputs.project-platform }}  -o .\bin\Release${{ inputs.package-id }}\ ${{ inputs.project-to-build }}

        $finalPackageFolder = ".\artifacts${{ inputs.package-id }}"
        Write-Host "Creating package folder: $finalPackageFolder"
        New-Item -ItemType Directory -Force -Path $finalPackageFolder

        $finalPackageName = "$finalPackageFolder\${{ inputs.package-id }}(${{ inputs.project-platform }})_${{ steps.gitversion.outputs.assemblySemVer }}.zip"
        Write-Host "Compressing final package: $finalPackageName"
        Compress-Archive -Path '.\bin\Release${{ inputs.package-id }}\*' -DestinationPath $finalPackageName

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: "${{ inputs.package-id }}(${{ inputs.project-platform }})_${{ steps.gitversion.outputs.assemblySemVer }}" 
        path: .\artifacts${{ inputs.package-id }}
        retention-days: ${{ inputs.artifact-retention-policy }}